"""agregar horarios_consultorio por dia

Revision ID: 1bce4cb456c7
Revises: b04150b939cb
Create Date: 2026-08-08 16:54:21.741935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bce4cb456c7'
down_revision = 'b04150b939cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horarios_consultorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_apertura', sa.Time(), nullable=True),
    sa.Column('hora_cierre', sa.Time(), nullable=True),
    sa.Column('cerrado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dia_semana')
    )
    # ### end Alembic commands ###

    # Backfill: heredar el horario global que ya existia.
    conn = op.get_bind()
    fila = conn.execute(sa.text(
        "SELECT horario_apertura, horario_cierre FROM configuracion_consultorio LIMIT 1"
    )).fetchone()
    apertura = fila[0] if fila and fila[0] else '09:00:00'
    cierre = fila[1] if fila and fila[1] else '18:00:00'
    for dia in range(7):
        conn.execute(
            sa.text("INSERT INTO horarios_consultorio "
                    "(dia_semana, hora_apertura, hora_cierre, cerrado) "
                    "VALUES (:d, :a, :c, :cer)"),
            {'d': dia, 'a': str(apertura), 'c': str(cierre), 'cer': 1 if dia == 6 else 0},
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horarios_consultorio')
    # ### end Alembic commands ###
