"""add logs_bot table

Revision ID: 36490ed1fd18
Revises: f241f920f95e
Create Date: 2026-04-12 21:01:24.586296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36490ed1fd18'
down_revision = 'f241f920f95e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'pacientes', ['tutor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
