"""add completada status, confirmacion_fecha, proximo_recordatorio_fecha

Revision ID: 375e3c99aa1a
Revises: 16d910afd5e2
Create Date: 2026-03-12 13:59:19.316145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375e3c99aa1a'
down_revision = '16d910afd5e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmacion_fecha', sa.DateTime(), nullable=True))

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proximo_recordatorio_fecha', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_column('proximo_recordatorio_fecha')

    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.drop_column('confirmacion_fecha')

    # ### end Alembic commands ###
