"""add real seguimiento types to TipoSeguimiento enum

Revision ID: 540c4f5af2b8
Revises: 36490ed1fd18
Create Date: 2026-07-13 16:38:45.846083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540c4f5af2b8'
down_revision = '36490ed1fd18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seguimientos_crm', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('confirmacion_cita', 'recordatorio_cita', 'post_consulta', 'reactivacion', 'presupuesto', 'tratamiento_pendiente', 'limpieza_control', 'anticipo_pendiente', 'resena', 'cumpleanos', 'whatsapp_1', 'whatsapp_2', 'llamada', name='tiposeguimiento'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seguimientos_crm', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.Enum('confirmacion_cita', 'recordatorio_cita', 'post_consulta', 'reactivacion', 'presupuesto', 'tratamiento_pendiente', 'limpieza_control', 'anticipo_pendiente', 'resena', 'cumpleanos', 'whatsapp_1', 'whatsapp_2', 'llamada', name='tiposeguimiento'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
