"""solicitud tipo + paciente_id

Revision ID: 69135314307b
Revises: e56e8a9202df
Create Date: 2026-08-01 18:29:43.508289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69135314307b'
down_revision = 'e56e8a9202df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTA: se omite intencionalmente el FK drift detectado en pacientes.tutor_id
    # (preexistente, fuera del alcance de esta migracion — Task 1 de
    # generalizacion de SolicitudRegistro). Solo se aplican los cambios de
    # solicitudes_registro.tipo / paciente_id.
    with op.batch_alter_table('solicitudes_registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=False, server_default='registro'))
        batch_op.add_column(sa.Column('paciente_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_solicitudes_registro_paciente_id', 'pacientes', ['paciente_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_registro', schema=None) as batch_op:
        batch_op.drop_constraint('fk_solicitudes_registro_paciente_id', type_='foreignkey')
        batch_op.drop_column('paciente_id')
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
