"""agregar fuera_de_horario a citas

Revision ID: b04150b939cb
Revises: 4448e15287da
Create Date: 2026-08-08 13:05:36.358912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b04150b939cb'
down_revision = '4448e15287da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuera_de_horario', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.drop_column('fuera_de_horario')

    # ### end Alembic commands ###
