"""add mensajes_enviados table and expand recordatorio enums

Revision ID: c9065cbec233
Revises: 69135314307b
Create Date: 2026-08-02 10:10:04.556396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9065cbec233'
down_revision = '69135314307b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # app.py ejecuta db.create_all() antes del autogenerate; la guarda permite
    # actualizar tanto esa BD local como instalaciones donde aún no exista.
    if not sa.inspect(op.get_bind()).has_table('mensajes_enviados'):
        op.create_table(
            'mensajes_enviados',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('tipo', sa.Enum(
                'confirmacion_24h', 'seguimiento_crm', 'cumpleanos',
                'postconsulta', 'sonrisas_magicas', 'confirmacion_mismo_dia',
                'proxima_visita', 'no_asistencia', 'resumen_doctor', 'campana',
                'manual', 'confirmacion_anticipo', 'otro',
                name='tiporecordatorio'), nullable=False),
            sa.Column('numero_destino', sa.String(length=20), nullable=False),
            sa.Column('mensaje', sa.Text(), nullable=False),
            sa.Column('paciente_id', sa.Integer(), nullable=True),
            sa.Column('cita_id', sa.Integer(), nullable=True),
            sa.Column('dentista_id', sa.Integer(), nullable=True),
            sa.Column('campana_destinatario_id', sa.Integer(), nullable=True),
            sa.Column('estatus', sa.Enum(
                'pendiente', 'enviado', 'fallido', 'fallido_definitivo',
                'caducado', name='estatusrecordatorio'), nullable=True),
            sa.Column('message_sid', sa.String(length=64), nullable=True),
            sa.Column('error', sa.Text(), nullable=True),
            sa.Column('intentos', sa.Integer(), nullable=False),
            sa.Column('proximo_intento', sa.DateTime(), nullable=True),
            sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
            sa.Column('fecha_envio', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id']),
            sa.ForeignKeyConstraint(['cita_id'], ['citas.id']),
            sa.ForeignKeyConstraint(['dentista_id'], ['dentistas.id']),
            sa.ForeignKeyConstraint(
                ['campana_destinatario_id'], ['campana_destinatarios.id']),
            sa.PrimaryKeyConstraint('id'),
        )
        op.create_index('ix_mensajes_enviados_tipo', 'mensajes_enviados', ['tipo'], unique=False)
        op.create_index(
            'ix_mensajes_enviados_numero_destino', 'mensajes_enviados',
            ['numero_destino'], unique=False)
        op.create_index('ix_mensajes_enviados_estatus', 'mensajes_enviados', ['estatus'], unique=False)
        op.create_index(
            'ix_mensajes_enviados_message_sid', 'mensajes_enviados',
            ['message_sid'], unique=False)
        op.create_index(
            'ix_mensajes_enviados_proximo_intento', 'mensajes_enviados',
            ['proximo_intento'], unique=False)
        op.create_index(
            'ix_mensajes_enviados_fecha_creacion', 'mensajes_enviados',
            ['fecha_creacion'], unique=False)

    with op.batch_alter_table('recordatorios', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('confirmacion_24h', 'seguimiento_crm', 'cumpleanos', 'postconsulta', 'sonrisas_magicas', 'confirmacion_mismo_dia', 'proxima_visita', 'no_asistencia', 'resumen_doctor', 'campana', 'manual', 'confirmacion_anticipo', 'otro', name='tiporecordatorio'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('pendiente', 'enviado', 'fallido', 'fallido_definitivo', 'caducado', name='estatusrecordatorio'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recordatorios', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pendiente', 'enviado', 'fallido', 'fallido_definitivo', 'caducado', name='estatusrecordatorio'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)
        batch_op.alter_column('tipo',
               existing_type=sa.Enum('confirmacion_24h', 'seguimiento_crm', 'cumpleanos', 'postconsulta', 'sonrisas_magicas', 'confirmacion_mismo_dia', 'proxima_visita', 'no_asistencia', 'resumen_doctor', 'campana', 'manual', 'confirmacion_anticipo', 'otro', name='tiporecordatorio'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    if sa.inspect(op.get_bind()).has_table('mensajes_enviados'):
        op.drop_index('ix_mensajes_enviados_fecha_creacion', table_name='mensajes_enviados')
        op.drop_index('ix_mensajes_enviados_proximo_intento', table_name='mensajes_enviados')
        op.drop_index('ix_mensajes_enviados_message_sid', table_name='mensajes_enviados')
        op.drop_index('ix_mensajes_enviados_estatus', table_name='mensajes_enviados')
        op.drop_index('ix_mensajes_enviados_numero_destino', table_name='mensajes_enviados')
        op.drop_index('ix_mensajes_enviados_tipo', table_name='mensajes_enviados')
        op.drop_table('mensajes_enviados')

    # ### end Alembic commands ###
