"""hora_resumen_doctores + pais dentista

Revision ID: e56e8a9202df
Revises: 540c4f5af2b8
Create Date: 2026-08-01 15:34:14.805798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e56e8a9202df'
down_revision = '540c4f5af2b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracion_consultorio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora_resumen_doctores', sa.Time(), nullable=True))

    with op.batch_alter_table('dentistas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pais', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dentistas', schema=None) as batch_op:
        batch_op.drop_column('pais')

    with op.batch_alter_table('configuracion_consultorio', schema=None) as batch_op:
        batch_op.drop_column('hora_resumen_doctores')

    # ### end Alembic commands ###
